name: Upload Extensions to Amazon S3
on:
  push:
    branches:
      - main
jobs:
  upload:
    name: Upload extensions to Amazon S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync . s3://${{ secrets.WEBINY_EXAMPLES_S3_BUCKET_NAME }}/v6 --delete --region ${{ secrets.AWS_REGION }} \
              --exclude ".*" \
              --exclude "node_modules*" \
              --exclude "package.json" \
              --exclude "README.md" \
              --exclude "yarn.lock"